### ISSUE TITLE
Compilation & packageBin issues

### ISSUE THREAD

**Issue by AnthonyVH** [ruippeixotog/ebay-snipe-server#3]
For some reason running "sbt universal:packageBin" on the latest commit (2bc80b262) does not produce any binaries. The only content in the generated zip-file is the logback.xml file (inside a subdir). There's no warnings during compilation, as far as I can see. Then again, nothing is compiled at all.

Going back 2 commits (to 6bebe341) fixes that, almost. Before being able to successfully run packageBin, the scala-scraper version in build.sbt needs to be changed from "1.1.0-SNAPSHOT" to "1.1.0". Otherwise there's an unmet dependency for scala-scraper during compilation.

Note that I did all compilation attempts by first running "git clean", then modifying build.sbt as noted above, and then running "sbt -no-shared universal:packageBin" (using the -no-shared to make sure it started with a clean slate).

**Comment by ruippeixotog** [comment]
Thank you for reporting this, @AnthonyVH! It was due to a bad migration to SBT 0.13.13 - in particular, a bad translation of [this](https://github.com/ruippeixotog/ebay-snipe-server/commit/62650509485f5580475a984148a0c8eafdbb1ef9#diff-fdc3abdfd754eeb24090dbd90aeec2ceL51) setting. Should be fine now.
