### ISSUE TITLE
Bids not registering on eBay, no error message

### ISSUE THREAD

**Issue by Hullgj** [ruippeixotog/ebay-snipe-server#4]
Just tried your app to place bids a few minutes in the future, using curl -X POST -H 'Content-Type: application/json' -d '{"bid": 1.0, "time":  ... It echoed back the request. After waiting for the time I noticed the bid didn't get posted to eBay.

I'm in BST but the server responds with the time an hour earlier, being GMT I guess. When submitting the post I compensate and adjust the time to GMT.

If that's not the problem, then could you confirm that your app still works please?

**Comment by ruippeixotog** [comment]
Hi @Hullgj, I haven't had time to do it yet, but I'll try to test the server this weekend.

**Comment by ruippeixotog** [comment]
Hello, I have just tried to place a bid via the server and everything worked as expected.

In order to check that the bidding code itself is working, you can try to schedule a bid for a past time and see that the bid is immediately executed:

```json
{
    "snipeTime": "1990-08-06T13:15:00",
    "bid": "USD 0.01"
}
```

Note that the price above must be valid for the auction.

Note also that even though `snipeTime` is always shown in the server time zone, you can schedule a snipe in a specific time zone:

```json
{
    "snipeTime": "2017-08-06T13:15:00+01:00",
    "bid": "USD 0.01"
}
```

Did this help?

**Comment by ruippeixotog** [comment]
I'll close this for now. Feel free to reopen the issue if you're still having problems with this :)
